export const Beds = [
  {
    name: "1",
    bed: [
      {
        name: "1",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "2",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "3",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "4",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "5",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
    ],
  },
  {
    name: "2",
    bed: [
      {
        name: "1",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "2",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "3",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "4",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
      {
        name: "5",
        respirationRatePCG: "",
        respirationRateAccel: "",
        temperature: "",
        fallDetection: "",
        deviceBattery: "",
        heartRatePCG: "",
        pulseRateECG: "",
        bodyPosture: "",
      },
    ],
  },
];
